repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
     #- id: infracost_breakdown
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
        args: ["--args=--lockfile=false"]
